accordion-padding = 30
after-login-command = []
automatically-unhide-macos-hidden-apps = false
default-root-container-layout = "accordion"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse window-lazy-center"]
start-at-login = false

[gaps.inner]
horizontal = 10
vertical = 10

[gaps.outer]
bottom = 7
left = 7
right = 10
top = 3

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-comma = "layout accordion horizontal vertical"
alt-shift-f = "fullscreen --no-outer-gaps"
alt-h = "focus --boundaries-action wrap-around-the-workspace left"
alt-j = "focus --boundaries-action wrap-around-the-workspace down"
alt-k = "focus --boundaries-action wrap-around-the-workspace up"
alt-l = "focus --boundaries-action wrap-around-the-workspace right"
alt-r = "mode resize"

alt-t = "exec-and-forget open -b com.github.wez.wezterm"
alt-w = "mode browser-selection"
alt-c = "exec-and-forget open -b com.tinyspeck.slackmacgap"
alt-e = "exec-and-forget open -b com.microsoft.Outlook"
alt-z = "exec-and-forget open -b us.zoom.xos"
alt-m = "exec-and-forget open -b com.apple.Music"

alt-shift-1 = [
  "move-node-to-workspace 1",
  # "layout tiles horizontal vertical",
]
alt-shift-2 = [
  "move-node-to-workspace 2",
  # "layout tiles horizontal vertical",
]
alt-shift-3 = [
  "move-node-to-workspace 3",
  # "layout accordion horizontal vertical",
]
alt-shift-4 = [
  "move-node-to-workspace 4",
  # "layout accordion horizontal vertical",
]
alt-shift-5 = [
  "move-node-to-workspace 5",
  # "layout tiles horizontal vertical",
]
alt-shift-c = "reload-config"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-semicolon = "mode service"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-slash = "layout tiles horizontal vertical"
alt-tab = "workspace-back-and-forth"
cmd-alt-h = []
cmd-h = []
cmd-m = []

[mode.service.binding]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
esc = ["reload-config", "mode main"]
f = ["layout floating tiling", "mode main"]
r = ["flatten-workspace-tree", "mode main"]

[mode.resize.binding]
h = "resize width -50"
j = "resize height -50"
k = "resize height +50"
l = "resize width +50"
enter = "mode main"
esc = "mode main"

[mode.browser-selection.binding]
s = ["exec-and-forget open -b com.apple.Safari", "mode main"]
e = ["exec-and-forget open -b com.microsoft.edgemac", "mode main"]
esc = "mode main"

[workspace-to-monitor-force-assignment]
m2 = ["secondary"]

# [[on-window-detected]]
# if.app-id = "com.microsoft.Outlook"
# run = ["move-node-to-workspace 1_daily"]
#
# [[on-window-detected]]
# if.app-id = "net.whatsapp.WhatsApp"
# run = ["move-node-to-workspace 1_daily"]
#
# [[on-window-detected]]
# if.app-id = "com.apple.reminders"
# run = ["layout floating", "move-node-to-workspace 1_daily"]
#
# [[on-window-detected]]
# if.app-id = "md.obsidian"
# run = "move-node-to-workspace 1_daily"
#
# [[on-window-detected]]
# if.app-id = "com.tinyspeck.slackmacgap"
# run = "move-node-to-workspace 2_connect"
#
# [[on-window-detected]]
# if.app-id = "us.zoom.xos"
# run = ["layout floating", "move-node-to-workspace 2_connect"]
#

[[on-window-detected]]
if.app-id = "com.apple.reminders"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = ["layout floating"]

# [[on-window-detected]]
# if.app-id = "com.github.wez.wezterm"
# run = "move-node-to-workspace 3_focus"
#
# [[on-window-detected]]
# if.app-id = "com.apple.Safari"
# run = "move-node-to-workspace 5_explore"

[[on-window-detected]]
if.app-id = "com.fasttracksoftware.adminbyrequest"
run = ["layout floating", "move-node-to-workspace ."]

[[on-window-detected]]
if.app-id = "com.1password.1password"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.Music"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.systempreferences"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.calculator"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.ActivityMonitor"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.PhotoBooth"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.finder"
if.window-title-regex-substring = "info|copy|move|delete|progress"
run = "layout floating"
